---
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: root

  tasks:

  - name: install ssh key
    authorized_key: user=root
                    key="{{ lookup('file', '/Users/shujinwu/.ssh/id_rsa.pub') }}"
                    state=present
